using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace osu__IRC
{
    static class Languages
    {
        public static Dictionary<string, string> languages = new Dictionary<string, string>()
        {
            {"English","ENG"}, //by ChrisYan n
            {"简体中文","CHS"}, //by ChrisYan n
            {"繁體中文","CHT"}, //by ChrisYan n
            {"Français","FRA"}, //by MrCraftCod n(20140814)
            {"Malay","MSA"}, //by mintong89 n(20140819)
			{"Italino","ITA"}, //by marcostudios n(20140825)
			{"한국어","KOR"}, //by koreapenguin n(20140825)
        };

        public static string GetString(string language, string strName)
        {
            string str = String.Empty;
            string idx = language + "_" + strName;
            try
            {
                str = languageContent[idx];
            }
            catch (KeyNotFoundException)
            {
                idx = "lang_" + strName;
                try
                {
                    str = languageContent[idx];
                }
                catch (KeyNotFoundException)
                {
#if DEBUG
                    System.Windows.Forms.MessageBox.Show("Missing String: " + idx);
#endif
                }
            }
            return str;
        }

        public static Dictionary<string, string> languageContent = new Dictionary<string, string>()
        {
            {"lang_UI_ToolStrip_Channels", "Channels"},
            {"lang_UI_ToolStrip_Language", "Language"},
            {"lang_UI_Login_Label_IRC_Password", "IRC Password"},
            {"lang_UI_Login_CheckBox_Remember_Password", "Remember Password"},
            {"lang_UI_Login_Button_Login", "Login"},
            {"lang_UI_Button_SendMessage", "Send"},
            {"lang_Ping_Label", "Ping: {0:F0}ms"},
            {"lang_Message_Welcome","Visit https://osu.ppy.sh/p/ircauth?action=allow&ip=osu!IRC and click 'Authorise IRC connection' to get your password"},
            {"lang_Message_Login_Wrong_Password","Login Fail! IRC Password Mismatch!"},
            {"lang_Message_Login_Logging_In","Logging in... ..."},
            {"lang_Message_Login_Success","Login Success!"},
            {"lang_Message_Login_Help","You can type /help to view command instructions"},
            {"lang_Message_Error_ChannelNotExist","The channel is not exist."},
            {"lang_Message_Error_UserNotExist","The user is not currently online."},
            {"lang_Message_Channel_Joining","Attempting to join {0}..."},
            {"lang_Message_Channel_Joined","Joined {0}!"},
            {"lang_Message_Channel_Message","[{0}] {1}: "},
            {"lang_Message_Channel_Message2","{0}"},
            {"lang_Message_Channel_Action","[{0}] "},
            {"lang_Message_Channel_Action2","*{0} {1}"},
            {"lang_Message_Channel_Not_Joined","You have not join {0} yet!"},
            {"lang_Message_PM_Message","[PM:{0}] {1} "},
            {"lang_Message_PM_Message2","{0}"},
            {"lang_Message_Help_Index","Command Help:"},
            {"lang_Message_Help_1a","/help"},
            {"lang_Message_Help_1b"," View this help."},
            {"lang_Message_Help_2a","/join <Channel>"},
            {"lang_Message_Help_2b"," Join a channel [ Example: /join #osu ]"},
            {"lang_Message_Help_3a","/part <Channel>"},
            {"lang_Message_Help_3b"," Leave a channel [ Example: /part #osu ]"},
            {"lang_Message_Help_4a","/me <Action>"},
            {"lang_Message_Help_4b"," Perform a third-person action."},
            {"lang_Message_Help_5a","/addfriend <Name>"},
            {"lang_Message_Help_5b"," Add a friend to the list [ Example: /addfriend BanchoBot ]"},
            {"lang_Message_Help_6a","/delfriend <Name>"},
            {"lang_Message_Help_6b"," Delete a friend from the list [ Example: /delfriend BanchoBot ]"},
            {"lang_Message_Command_me_Empty_Parameter","/me <Action>"},
            {"lang_Message_Command_join_Empty_Parameter","/join <Channel>"},
            {"lang_Message_Command_part_Empty_Parameter","/part <Channel>"},
            {"lang_Message_Command_addfriend_Exist","{0} is already on your list"},
            {"lang_Message_Command_delfriend_Not_Exist","{0} doesn't exist on your list"},

            {"ENG_UI_ToolStrip_Channels", "Channels"},
            {"ENG_UI_ToolStrip_Language", "Language"},
            {"ENG_UI_Login_Label_IRC_Password", "IRC Password"},
            {"ENG_UI_Login_CheckBox_Remember_Password", "Remember Password"},
            {"ENG_UI_Login_Button_Login", "Login"},
            {"ENG_UI_Button_SendMessage", "Send"},
            {"ENG_Ping_Label", "Ping: {0:F0}ms"},
            {"ENG_Message_Welcome","Visit https://osu.ppy.sh/p/ircauth?action=allow&ip=osu!IRC and click 'Authorise IRC connection' to get your password"},
            {"ENG_Message_Login_Wrong_Password","Login Fail! IRC Password Mismatch!"},
            {"ENG_Message_Login_Logging_In","Logging in... ..."},
            {"ENG_Message_Login_Success","Login Success!"},
            {"ENG_Message_Login_Help","You can type /help to view command instructions"},
            {"ENG_Message_Error_ChannelNotExist","The channel is not exist."},
            {"ENG_Message_Error_UserNotExist","The user is not currently online."},
            {"ENG_Message_Channel_Joining","Attempting to join {0}..."},
            {"ENG_Message_Channel_Joined","Joined {0}!"},
            {"ENG_Message_Channel_Message","[{0}] {1}: "},
            {"ENG_Message_Channel_Message2","{0}"},
            {"ENG_Message_Channel_Action","[{0}] "},
            {"ENG_Message_Channel_Action2","*{0} {1}"},
            {"ENG_Message_Channel_Not_Joined","You have not join {0} yet!"},
            {"ENG_Message_PM_Message","[PM:{0}] {1} "},
            {"ENG_Message_PM_Message2","{0}"},
            {"ENG_Message_Help_Index","Command Help:"},
            {"ENG_Message_Help_1a","/help"},
            {"ENG_Message_Help_1b"," View this help."},
            {"ENG_Message_Help_2a","/join <Channel>"},
            {"ENG_Message_Help_2b"," Join a channel [ Example: /join #osu ]"},
            {"ENG_Message_Help_3a","/part <Channel>"},
            {"ENG_Message_Help_3b"," Leave a channel [ Example: /part #osu ]"},
            {"ENG_Message_Help_4a","/me <Action>"},
            {"ENG_Message_Help_4b"," Perform a third-person action."},
            {"ENG_Message_Help_5a","/addfriend <Name>"},
            {"ENG_Message_Help_5b"," Add a friend to the list [ Example: /addfriend BanchoBot ]"},
            {"ENG_Message_Help_6a","/delfriend <Name>"},
            {"ENG_Message_Help_6b"," Delete a friend from the list [ Example: /delfriend BanchoBot ]"},
            {"ENG_Message_Command_me_Empty_Parameter","/me <Action>"},
            {"ENG_Message_Command_join_Empty_Parameter","/join <Channel>"},
            {"ENG_Message_Command_part_Empty_Parameter","/part <Channel>"},
            {"ENG_Message_Command_addfriend_Exist","{0} is already on your list"},
            {"ENG_Message_Command_delfriend_Not_Exist","{0} doesn't exist on your list"},

            {"CHT_UI_ToolStrip_Channels", "頻道"},
            {"CHT_UI_ToolStrip_Language", "語言"},
            {"CHT_UI_Login_Label_IRC_Password", "IRC密碼"},
            {"CHT_UI_Login_CheckBox_Remember_Password", "記住密碼"},
            {"CHT_UI_Login_Button_Login", "登入"},
            {"CHT_UI_Button_SendMessage", "發送"},
            {"CHT_Ping_Label", "延時: {0:F0}ms"},
            {"CHT_Message_Welcome","你可以在 https://osu.ppy.sh/p/ircauth?action=allow&ip=osu!IRC 點擊 'Authorise IRC connection' 來取得你的IRC密碼"},
            {"CHT_Message_Login_Wrong_Password","登入失敗 IRC密碼無效!"},
            {"CHT_Message_Login_Logging_In","登入中... ..."},
            {"CHT_Message_Login_Success","登入成功!"},
            {"CHT_Message_Login_Help","你可以輸入/help查看指令幫助"},
            {"CHT_Message_Error_ChannelNotExist","該頻道不存在"},
            {"CHT_Message_Error_UserNotExist","該用戶不在線上"},
            {"CHT_Message_Channel_Joining","嘗試加入頻道 {0}..."},
            {"CHT_Message_Channel_Joined","你加入了 {0}!"},
            {"CHT_Message_Channel_Message","[{0}] {1}: "},
            {"CHT_Message_Channel_Message2","{0}"},
            {"CHT_Message_Channel_Action","[{0}] "},
            {"CHT_Message_Channel_Action2","*{0} {1}"},
            {"CHT_Message_Channel_Not_Joined","你尚未加入 {0}!"},
            {"CHT_Message_PM_Message","[PM:{0}] {1} "},
            {"CHT_Message_PM_Message2","{0}"},
            {"CHT_Message_Help_Index","指令幫助:"},
            {"CHT_Message_Help_1a","/help"},
            {"CHT_Message_Help_1b"," 查看此幫助."},
            {"CHT_Message_Help_2a","/join <Channel>"},
            {"CHT_Message_Help_2b"," 加入頻道 [ 例子: /join #osu ]"},
            {"CHT_Message_Help_3a","/part <Channel>"},
            {"CHT_Message_Help_3b"," 離開頻道 [ 例子: /part #osu ]"},
            {"CHT_Message_Help_4a","/me <Action>"},
            {"CHT_Message_Help_4b"," 以第三人稱發送自己的動作訊息"},
            {"CHT_Message_Help_5a","/addfriend <Name>"},
            {"CHT_Message_Help_5b"," 增加一個常用聯絡人到列表中 [ 例子: /addfriend BanchoBot ]"},
            {"CHT_Message_Help_6a","/delfriend <Name>"},
            {"CHT_Message_Help_6b"," 從常用聯絡人列表刪除指定對象 [ 例子: /delfriend BanchoBot ]"},
            {"CHT_Message_Command_me_Empty_Parameter","/me <Action>"},
            {"CHT_Message_Command_join_Empty_Parameter","/join <Channel>"},
            {"CHT_Message_Command_part_Empty_Parameter","/part <Channel>"},
            {"CHT_Message_Command_addfriend_Exist","{0} 已在你的列表中"},
            {"CHT_Message_Command_delfriend_Not_Exist","{0} 不存在你的列表中"},

            {"CHS_UI_ToolStrip_Channels", "频道"},
            {"CHS_UI_ToolStrip_Language", "语言"},
            {"CHS_UI_Login_Label_IRC_Password", "IRC验证码"},
            {"CHS_UI_Login_CheckBox_Remember_Password", "记住验证码"},
            {"CHS_UI_Login_Button_Login", "登录"},
            {"CHS_UI_Button_SendMessage", "发送"},
            {"CHS_Ping_Label", "延时: {0:F0}毫秒"},
            {"CHS_Message_Welcome","访问 https://osu.ppy.sh/p/ircauth?action=allow&ip=osu!IRC 并点击 'Authorise IRC connection' 获取你的IRC验证码"},
            {"CHS_Message_Login_Wrong_Password","登录失败 密码错误!"},
            {"CHS_Message_Login_Logging_In","登录中... ..."},
            {"CHS_Message_Login_Success","登录成功!"},
            {"CHS_Message_Login_Help","你可以输入/help查看指令帮助"},
            {"CHS_Message_Error_ChannelNotExist","该频道不存在"},
            {"CHS_Message_Error_UserNotExist","该用户不在线"},
            {"CHS_Message_Channel_Joining","尝试加入 {0} 频道..."},
            {"CHS_Message_Channel_Joined","你加入了 {0}!"},
            {"CHS_Message_Channel_Message","[{0}] {1}: "},
            {"CHS_Message_Channel_Message2","{0}"},
            {"CHS_Message_Channel_Action","[{0}] "},
            {"CHS_Message_Channel_Action2","*{0} {1}"},
            {"CHS_Message_Channel_Not_Joined","你尚未加入 {0}!"},
            {"CHS_Message_PM_Message","[PM:{0}] {1} "},
            {"CHS_Message_PM_Message2","{0}"},
            {"CHS_Message_Help_Index","指令帮助:"},
            {"CHS_Message_Help_1a","/help"},
            {"CHS_Message_Help_1b"," 查看此帮助."},
            {"CHS_Message_Help_2a","/join <Channel>"},
            {"CHS_Message_Help_2b"," 加入频道 [ 例子: /join #osu ]"},
            {"CHS_Message_Help_3a","/part <Channel>"},
            {"CHS_Message_Help_3b"," 加入频道 [ 例子: /part #osu ]"},
            {"CHS_Message_Help_4a","/me <Action>"},
            {"CHS_Message_Help_4b"," 以第三人称发送自己的动作信息"},
            {"CHS_Message_Help_5a","/addfriend <Name>"},
            {"CHS_Message_Help_5b"," 增加常用联络人到列表中 [ 例子: /addfriend BanchoBot ]"},
            {"CHS_Message_Help_6a","/delfriend <Name>"},
            {"CHS_Message_Help_6b"," 删除自定常用联络人 [ 例子: /delfriend BanchoBot ]"},
            {"CHS_Message_Command_me_Empty_Parameter","/me <Action>"},
            {"CHS_Message_Command_join_Empty_Parameter","/join <Channel>"},
            {"CHS_Message_Command_part_Empty_Parameter","/part <Channel>"},
            {"CHS_Message_Command_addfriend_Exist","{0} 已在你的列表里"},
            {"CHS_Message_Command_delfriend_Not_Exist","{0} 不在你的列表里"},

            {"FRA_UI_ToolStrip_Channels", "Canaux"},
            {"FRA_UI_ToolStrip_Language", "Langues"},
            {"FRA_UI_Login_Label_IRC_Password", "Mot de passe IRC"},
            {"FRA_UI_Login_CheckBox_Remember_Password", "Retenir le mot de passe"},
            {"FRA_UI_Login_Button_Login", "Connexion"},
            {"FRA_UI_Button_SendMessage", "Envoyer"},
            {"FRA_Ping_Label", "Ping: {0:F0}ms"},
            {"FRA_Message_Welcome","Rendez-vous sur https://osu.ppy.sh/p/ircauth?action=allow&ip=osu!IRC et cliquez sur 'Authorise IRC connection' pour obtenir votre mot de passe"},
            {"FRA_Message_Login_Wrong_Password","Erreur de connexion! Le mot de passe n'est pas valide!"},
            {"FRA_Message_Login_Logging_In","Connexion en cours... ..."},
            {"FRA_Message_Login_Success","Connexion réussie!"},
            {"FRA_Message_Login_Help","Tapez /help pour accéder aux aides des commandes"},
            {"FRA_Message_Error_ChannelNotExist","Le canal n'existe pas."},
            {"FRA_Message_Error_UserNotExist","Cet utilisateur n'est pas en ligne"},
            {"FRA_Message_Channel_Joining","Tentative de connexion sur {0}..."},
            {"FRA_Message_Channel_Joined","{0} rejoint!"},
            {"FRA_Message_Channel_Message","[{0}] {1}: "},
            {"FRA_Message_Channel_Message2","{0}"},
            {"FRA_Message_Channel_Action","[{0}] "},
            {"FRA_Message_Channel_Action2","*{0} {1}"},
            {"FRA_Message_Channel_Not_Joined","Vous n'avez pas encore rejoint {0}!"},
            {"FRA_Message_PM_Message","[MP:{0}] {1} "},
            {"FRA_Message_PM_Message2","{0}"},
            {"FRA_Message_Help_Index","Aide des commandes:"},
            {"FRA_Message_Help_1a","/help"},
            {"FRA_Message_Help_1b"," Voir cet aide."},
            {"FRA_Message_Help_2a","/join <Canal>"},
            {"FRA_Message_Help_2b"," Rejoint un canal [ Exemple: /join #osu ]"},
            {"FRA_Message_Help_3a","/part <Canal>"},
            {"FRA_Message_Help_3b"," Quitte un canal [ Exemple: /part #osu ]"},
            {"FRA_Message_Help_4a","/me <Action>"},
            {"FRA_Message_Help_4b"," Effectuer une action à la 3éme personne."},
            {"FRA_Message_Help_5a","/addfriend <Name>"},
            {"FRA_Message_Help_5b"," Ajouter une personne à la liste d'amis [ Exemple: /addfriend BanchoBot ]"},
            {"FRA_Message_Help_6a","/delfriend <Name>"},
            {"FRA_Message_Help_6b"," Retirer une personne de la liste d'amis [ Exemple: /delfriend BanchoBot ]"},
            {"FRA_Message_Command_me_Empty_Parameter","/me <Action>"},
            {"FRA_Message_Command_join_Empty_Parameter","/join <Canal>"},
            {"FRA_Message_Command_part_Empty_Parameter","/part <Canal>"},
            {"FRA_Message_Command_addfriend_Exist","{0} est déjà dans vos amis"},
            {"FRA_Message_Command_delfriend_Not_Exist","{0} n'est pas dans vos amis"},

			{"MSA_UI_ToolStrip_Channels", "Saluran"},
			{"MSA_UI_ToolStrip_Language", "Bahasa"},
			{"MSA_UI_Login_Label_IRC_Password", "Kata Laluan IRC"},
			{"MSA_UI_Login_CheckBox_Remember_Password", "Ingat Kata Laluan"},
			{"MSA_UI_Login_Button_Login", "Log Masuk"},
			{"MSA_UI_Button_SendMessage", "Hantar"},
			{"MSA_Ping_Label", "Ping: {0:F0}ms"},
			{"MSA_Message_Welcome","Melawat https://osu.ppy.sh/p/ircauth?action=allow&ip=osu!IRC dan kilk 'Authorise IRC connection' untuk mendapatkan kata laluan anda."},
			{"MSA_Message_Login_Wrong_Password","Log masuk gagal kerana kata laluan salah!"},
			{"MSA_Message_Login_Logging_In","Sedang Log Masuk..."},
			{"MSA_Message_Login_Success","Berjaya Log Masuk!"},
			{"MSA_Message_Login_Help","Anda boleh menaip /help untuk melihat arahan command"},
			{"MSA_Message_Error_ChannelNotExist","Saluran ini tidak wujud."},
			{"MSA_Message_Error_UserNotExist","Pemain ini tidak wujud atau tidak online."},
			{"MSA_Message_Channel_Joining","Sedang menyertai {0}..."},
			{"MSA_Message_Channel_Joined","Menyertai {0}!"},
			{"MSA_Message_Channel_Message","[{0}] {1}: "},
			{"MSA_Message_Channel_Message2","{0}"},
			{"MSA_Message_Channel_Action","[{0}] "},
			{"MSA_Message_Channel_Action2","*{0} {1}"},
			{"MSA_Message_Channel_Not_Joined","Kamu belum menyertai channel {0} lagi!"},
			{"MSA_Message_PM_Message","[PM:{0}] {1} "},
			{"MSA_Message_PM_Message2","{0}"},
			{"MSA_Message_Help_Index","Arahan Command:"},
			{"MSA_Message_Help_1a","/help"},
			{"MSA_Message_Help_1b"," Lihat help ini."},
			{"MSA_Message_Help_2a","/join <Saluran>"},
			{"MSA_Message_Help_2b"," Menyertai saluran [ Contoh: /join #osu ]"},
			{"MSA_Message_Help_3a","/part <Saluran>"},
			{"MSA_Message_Help_3b"," Tinggalkan saluran [ Contoh: /part #osu ]"},
			{"MSA_Message_Help_4a","/me <Tindakan>"},
			{"MSA_Message_Help_4b"," Lakukan tindakan orang ketiga"},
			{"MSA_Message_Help_5a","/addfriend <Nama>"},
			{"MSA_Message_Help_5b"," Menambahkan kawan ke dalam senarai [ Contoh: /addfriend BanchoBot ]"},
			{"MSA_Message_Help_6a","/delfriend <Nama>"},
			{"MSA_Message_Help_6b"," Padam kawan dari senarai [ Example: /delfriend BanchoBot ]"},
			{"MSA_Message_Command_me_Empty_Parameter","/me <Tindakan>"},
			{"MSA_Message_Command_join_Empty_Parameter","/join <Saluran>"},
			{"MSA_Message_Command_part_Empty_Parameter","/part <Saluran>"},
			{"MSA_Message_Command_addfriend_Exist","{0} sudah di senarai anda"},
			{"MSA_Message_Command_delfriend_Not_Exist","{0} tidak wujud di senarai anda"},
			
			{"ITA_UI_ToolStrip_Channels", "Canali"},
			{"ITA_UI_ToolStrip_Language", "Lingua"},
			{"ITA_UI_Login_Label_IRC_Password", "Password IRC"},
			{"ITA_UI_Login_CheckBox_Remember_Password", "Ricorda la Password"},
			{"ITA_UI_Login_Button_Login", "Login"},
			{"ITA_UI_Button_SendMessage", "Invia"},
			{"ITA_Ping_Label", "Ping: {0:F0}ms"},
			{"ITA_Message_Welcome","Visita https://osu.ppy.sh/p/ircauth?action=allow&ip=osu!IRC e clicca 'Authorise IRC connection' per avere la tua password"},
			{"ITA_Message_Login_Wrong_Password","Login Fallito! La password IRC non corrisponde!"},
			{"ITA_Message_Login_Logging_In","Accesso in corso... ..."},
			{"ITA_Message_Login_Success","Accesso riuscito!"},
			{"ITA_Message_Login_Help","Puoi scrivere /help per vedere le istruzioni sui comandi"},
			{"ITA_Message_Error_ChannelNotExist","Il canale non esiste."},
			{"ITA_Message_Error_UserNotExist","L'utente non è al momento online."},
			{"ITA_Message_Channel_Joining","Tentativo di collegarsi a {0}..."},
			{"ITA_Message_Channel_Joined","Collegato a {0}!"},
			{"ITA_Message_Channel_Message","[{0}] {1}: "},
			{"ITA_Message_Channel_Message2","{0}"},
			{"ITA_Message_Channel_Action","[{0}] "},
			{"ITA_Message_Channel_Action2","*{0} {1}"},
			{"ITA_Message_Channel_Not_Joined","Non sei ancora collegato a {0}!"},
			{"ITA_Message_PM_Message","[Messaggio Privato:{0}] {1} "},
			{"ITA_Message_PM_Message2","{0}"},
			{"ITA_Message_Help_Index","Aiuto sui comandi:"},
			{"ITA_Message_Help_1a","/help"},
			{"ITA_Message_Help_1b"," Visualizza questa guida."},
			{"ITA_Message_Help_2a","/join <Canale>"},
			{"ITA_Message_Help_2b"," Entra in un canale [ Esempio: /join #osu ]"},
			{"ITA_Message_Help_3a","/part <Canale>"},
			{"ITA_Message_Help_3b"," Lascia un canale [ Esempio: /part #osu ]"},
			{"ITA_Message_Help_4a","/me <Azione>"},
			{"ITA_Message_Help_4b"," Esegui un'azione in terza persona."},
			{"ITA_Message_Help_5a","/addfriend <Nome>"},
			{"ITA_Message_Help_5b"," Aggiunge un amico alla lista[ Esempio: /addfriend BanchoBot ]"},
			{"ITA_Message_Help_6a","/delfriend <Nome>"},
			{"ITA_Message_Help_6b"," Rimuove un amico dalla lista [ Esempio: /delfriend BanchoBot ]"},
			{"ITA_Message_Command_me_Empty_Parameter","/me <Azione>"},
			{"ITA_Message_Command_join_Empty_Parameter","/join <Canale>"},
			{"ITA_Message_Command_part_Empty_Parameter","/part <Canale>"},
			{"ITA_Message_Command_addfriend_Exist","{0} è gia nella tua lista"},
			{"ITA_Message_Command_delfriend_Not_Exist","{0} non esiste nella tua lista"}, 
			
			{"KOR_UI_ToolStrip_Channels", "채널"},
			{"KOR_UI_ToolStrip_Language", "언어"},
			{"KOR_UI_Login_Label_IRC_Password", "IRC 비밀번호"},
			{"KOR_UI_Login_CheckBox_Remember_Password", "비밀번호 저장"},
			{"KOR_UI_Login_Button_Login", "로그인"},
			{"KOR_UI_Button_SendMessage", "보내기"},
			{"KOR_Ping_Label", "Ping: {0:F0}ms"},
			{"KOR_Message_Welcome","https://osu.ppy.sh/p/ircauth?action=allow&ip=osu!IRC 이 곳을 클릭 'Authorise IRC connection' 에서 비밀번호를 확인"},
			{"KOR_Message_Login_Wrong_Password","로그인 실패! IRC 비밀번호가 옳바르지 않습니다!"},
			{"KOR_Message_Login_Logging_In","로그인 중... ..."},
			{"KOR_Message_Login_Success","로그인 성공!"},
			{"KOR_Message_Login_Help","/help 명령어를 이용하여 각종 커맨드확인이 가능합니다."},
			{"KOR_Message_Error_ChannelNotExist","이 채널은 존재하지 않습니다."},
			{"KOR_Message_Error_UserNotExist","존재하지 않는 유저입니다."},
			{"KOR_Message_Channel_Joining","{0}에 가입하는중..."},
			{"KOR_Message_Channel_Joined","{0}에 접속!"},
			{"KOR_Message_Channel_Message","[{0}] {1}: "},
			{"KOR_Message_Channel_Message2","{0}"},
			{"KOR_Message_Channel_Action","[{0}] "},
			{"KOR_Message_Channel_Action2","*{0} {1}"},
			{"KOR_Message_Channel_Not_Joined","아직 {0}에 접속하지 않았습니다!"},
			{"KOR_Message_PM_Message","[PM:{0}] {1} "},
			{"KOR_Message_PM_Message2","{0}"},
			{"KOR_Message_Help_Index","명령어:"},
			{"KOR_Message_Help_1a","/help"},
			{"KOR_Message_Help_1b"," 각종 명령어를 보여줍니다."},
			{"KOR_Message_Help_2a","/join <채널이름>"},
			{"KOR_Message_Help_2b"," 해당 채널에 접속합니다. [ 예: /join #osu ]"},
			{"KOR_Message_Help_3a","/part <채널이름>"},
			{"KOR_Message_Help_3b"," 해당 채널에서 나갑니다. [ 예: /part #osu ]"},
			{"KOR_Message_Help_4a","/me <할말>"},
			{"KOR_Message_Help_4b"," 할 말을 3인칭으로 표현합니다."},
			{"KOR_Message_Help_5a","/addfriend <유저명>"},
			{"KOR_Message_Help_5b"," 해당 유저를 친구목록에 추가합니다. [ 예: /addfriend BanchoBot ]"},
			{"KOR_Message_Help_6a","/delfriend <유저명>"},
			{"KOR_Message_Help_6b"," 친구목록에서 해당유저를 삭제합니다. [ 예: /delfriend BanchoBot]"},
			{"KOR_Message_Command_me_Empty_Parameter","/me <할말>"},
			{"KOR_Message_Command_join_Empty_Parameter","/join <채널>"},
			{"KOR_Message_Command_part_Empty_Parameter","/part <채널>"},
			{"KOR_Message_Command_addfriend_Exist","{0}은(는) 이미 친구목록에 있습니다."},
			{"KOR_Message_Command_delfriend_Not_Exist","{0}은(는) 더 이상 목록에 존재하지 않습니다."},
        };

    }
}